Task/impovements
avtocod/python-developer-test-task pull request #3
Opened 2020-02-13 10:50 UTC by own3dh4rd

| Q             | A
| ------------- | ---
| Bug fix?      | No
| New feature?  | Yes

## Description

* Updated README.md and added docker & makefile to quickly start development
* CI

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I wrote unit tests for my code _(if tests is required for my changes)_
- [ ] I have made changes in `CHANGELOG.md` file

2020-02-14 17:44 UTC, tarampampam requested changes

2020-02-14 17:44 UTC, tarampampam commented on .dockerignore
> +**/*.pyc
Вхождения `.gitlab-ci.yml`, `.gitlab`, `readme`, `scripts` кажутся лишними, у уверен ли в том что `**/__pycache__` будет корректно работать? Просто `*` должны работают, а `**` - что-то засомневался

2020-02-14 17:44 UTC, tarampampam commented on .editorconfig
> +[*.{yml, yaml, sh, conf, neon, neon.dist}]
`, neon, neon.dist` - не используются и, кажется, не планируются :) Уберём?

2020-02-14 17:44 UTC, tarampampam commented on .editorconfig
> +max_line_length = 80
не `120`?

2020-02-14 17:44 UTC, tarampampam commented on .github/workflows/build.yml
> +name: Python package
Обычно используются имена `Tests`, `CI` или что-то на то похожее (это же имя конвеера)

2020-02-14 17:44 UTC, tarampampam commented on .github/workflows/build.yml
> +        pip install -r requirements.txt
Может быть разбить на 2 отдельных шага? Например:

```yaml
    - name: Install latest PIP
      run: python -m pip install --upgrade pip

    - name: Install dependencies
      run: pip install -r requirements.txt
```

И символы табуляции вперемешку с пробелами в этом yaml-файле присутствуют. Лучше бы на пробелы заменить

2020-02-14 17:44 UTC, tarampampam commented on .github/workflows/build.yml
> +        flake8 .
Как смотришь на то, чтоб ставить dev-зависимости силами `pip install -r requirements-dev.txt` одним шагом, а потом 2 других - это соответственно поочередный вызов `flake8 .` и `pytest`? (`flake8` внести в `requirements-dev.txt`)

2020-02-14 17:44 UTC, tarampampam commented on .gitignore
> +*.so
Выглядим очень внушительно :) Понимаю, что это наверняка какой-то шаблон из "лучших практик" но, возможно, есть смысл оставить только то что действительно надо заигнорить с **минимальным** набором того, что вероятнее всего потребуется дополнительно?

2020-02-14 17:44 UTC, tarampampam commented on Dockerfile
> +FROM python:3-alpine
Возможно версию лучше фиксировать до минора? Т.е. `python:3.8-alpine`

2020-02-14 17:44 UTC, tarampampam commented on Dockerfile
> +COPY ./requirements-dev.txt /requirements-dev.txt
Как на счет `COPY ./requirements* /` одним слоем (и может быть лучше не в корень а предварительно созданную директорию `/app`)?

2020-02-14 17:44 UTC, tarampampam commented on Makefile
> +pull: ## Pulling newer versions of used docker images
`pull` выглядит не имеющим смысла, так как не используется какой-либо образ :)

2020-02-14 17:44 UTC, tarampampam commented on Makefile
> +restart: shutdown start ## Restart all containers
Так как нет сервисов - нужно ли поставлять данные цели?

2020-02-14 17:44 UTC, tarampampam commented on requirements-dev.txt
> +pytest
Фиксирование диапазоном версий для `pytest` не принято?

2020-02-18 06:41 UTC, own3dh4rd commented on .editorconfig
> +max_line_length = 80
80

2020-02-18 06:42 UTC, own3dh4rd commented on Dockerfile
> +FROM python:3-alpine
В тестовом любой 3ий питон, кандидат может сам выбрать изменив строчку

2020-02-18 06:46 UTC, own3dh4rd commented on .dockerignore
> +**/*.pyc
А зачем нам в докере  `.gitlab-ci.yml`, `.gitlab`, `readme`, `script`? Кстати, это копипаста того докеригнора, который, кажется, ты же и делал.

** - работает и легко гуглится

2020-02-18 06:48 UTC, own3dh4rd commented on Makefile
> +restart: shutdown start ## Restart all containers
Как минимум один есть - app, пусть будет

2020-02-18 06:49 UTC, own3dh4rd commented on .editorconfig
> +[*.{yml, yaml, sh, conf, neon, neon.dist}]
Изи

2020-02-18 06:52 UTC, own3dh4rd commented on .gitignore
> +*.so
Это долго сидеть и разбирать 100 строк всяких расширений. Пацаны сделали - я пользуюсь.

2020-02-18 06:52 UTC, own3dh4rd commented on Makefile
> +pull: ## Pulling newer versions of used docker images
Норм

2020-02-18 06:53 UTC, own3dh4rd commented on requirements-dev.txt
> +pytest
Не часто видел, но сам бывало фиксировал, когда действительно тесты падали после обновления

Это шаблон и любой кандидат сможет зафиксировать версию, которая ему нужна

2020-02-18 06:57 UTC, own3dh4rd commented on .github/workflows/build.yml
> +        pip install -r requirements.txt
Сделал рефактор в ide, надеюсь он зафиксит

2020-02-18 06:58 UTC, own3dh4rd commented on .github/workflows/build.yml
> +        flake8 .
Я на это смотрю так: сейчас это сделать можно, так как всего две зависимости, но не имеет смысла, когда dev-зависимости разрастутся

2020-02-18 06:59 UTC, own3dh4rd commented on .github/workflows/build.yml
> +name: Python package
Переименовал на `CI`

2020-02-18 07:00 UTC, own3dh4rd commented on .github/workflows/build.yml
> +        pip install -r requirements.txt
Насчет разбиения - хз, и то и то выглядит норм

2020-02-18 07:22 UTC, own3dh4rd commented on Dockerfile
> +COPY ./requirements-dev.txt /requirements-dev.txt
Переделал

2020-02-18 07:28 UTC, own3dh4rd commented on Dockerfile
> +FROM python:3-alpine
Короче, поменял версию питона

Минималка теперь 3.6, устанавливаться в докере будет последняя на сегодняшний день

2020-02-18 16:55 UTC, tarampampam commented on .dockerignore
> +**/*.pyc
Проекты-то разные :) `.gitlab-ci.yml`, `.gitlab`, `readme`, `scripts` тут точно лишние

2020-02-18 16:57 UTC, tarampampam commented on .github/workflows/build.yml
> +        pip install -r requirements.txt
Давай всё-таки разобьём на отдельные шаги; один шаг - одно действие

2020-02-18 16:59 UTC, tarampampam commented on .github/workflows/build.yml
> +        flake8 .
Читаемости ради и явного указания того, что используется для тестирования - давай всё таки укажем `flake8` в `requirements-dev.txt` и добавим отдельный шаг с `pip install -r requirements-dev.txt`, пожалуйста

2020-02-18 17:00 UTC, tarampampam commented on .gitignore
> +*.so
Но порядка 70% не используется и использоваться будет вряд ли. Less code is better, ever :)

2020-02-18 17:01 UTC, tarampampam commented on Dockerfile
> +FROM python:3-alpine
:+1:

2020-02-18 17:03 UTC, tarampampam commented on Makefile
> +.PHONY : help init install shell test lint pull start shutdown restart logs clean
Тут ещё `pull` остался

2020-02-18 17:03 UTC, tarampampam commented on requirements-dev.txt
> +pytest
:+1:

2020-02-20 12:21 UTC, tarampampam approved these changes

2020-02-20 12:22 UTC, merged

2020-02-20 12:25 UTC, tarampampam commented
@own3dh4rd great job!